apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  labels:
    type: redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: redis
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /redis/data
    server: #enterserver
