---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-claim
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis
  resources:
    requests:
      storage: 20Gi
