apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server
spec:
  selector:
    matchLabels:
      app: redis
      role: server
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: server
        tier: backend
    spec:
      containers:
      - name: master
        image: eldhodoc/redisserver
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-claim
